// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2OtJ6VmlK2zY61C1nt48m-KkRaJW-VmM',
    appId: '1:93278819338:web:22255d3908adde5f073bf3',
    messagingSenderId: '93278819338',
    projectId: 'disaster-notify',
    authDomain: 'disaster-notify.firebaseapp.com',
    storageBucket: 'disaster-notify.appspot.com',
    measurementId: 'G-NZ9QG4XPC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1kKdRasd8bcDKxQIuFN6wfh25jofLTkA',
    appId: '1:93278819338:android:73748faa955a2c41073bf3',
    messagingSenderId: '93278819338',
    projectId: 'disaster-notify',
    storageBucket: 'disaster-notify.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyjBFporOh1qGn-fCn184IUq_YdkL3OJo',
    appId: '1:93278819338:ios:8b2c14e4c20a809e073bf3',
    messagingSenderId: '93278819338',
    projectId: 'disaster-notify',
    storageBucket: 'disaster-notify.appspot.com',
    iosBundleId: 'com.example.flutterNotifyTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyjBFporOh1qGn-fCn184IUq_YdkL3OJo',
    appId: '1:93278819338:ios:8b2c14e4c20a809e073bf3',
    messagingSenderId: '93278819338',
    projectId: 'disaster-notify',
    storageBucket: 'disaster-notify.appspot.com',
    iosBundleId: 'com.example.flutterNotifyTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2OtJ6VmlK2zY61C1nt48m-KkRaJW-VmM',
    appId: '1:93278819338:web:d997c2d71fe3630a073bf3',
    messagingSenderId: '93278819338',
    projectId: 'disaster-notify',
    authDomain: 'disaster-notify.firebaseapp.com',
    storageBucket: 'disaster-notify.appspot.com',
    measurementId: 'G-LGTSNWMV3G',
  );

}